### ISSUE TITLE
minor clarification of ucorrelate description

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [OpenSMFS/pycorrelate#3]
The documentation for ucorrelate says the following: "The classical text-book linear cross-correlation between two signals defined at uniformly spaced intervals."  I know that it is fairly obvious, but it would nevertheless be good to restate as follows: "The classical textbook linear cross-correlation between two signals defined at uniformly-spaced intervals **with the same interval size.**"

**Comment by tritemio** [comment]
Thanks for your input, we always welcome clarifications to the docs.

To your point,  "uniformly-spaced intervals" already means "with the same interval size", no? We should add the missing dash though.

**Comment by Phillip-M-Feldman** [comment]
The current wording allows for the possibility that one time series is
uniformly-spaced with an interval of 1 second, while the second is
uniformly-spaced with an interval of 2 seconds.  I'm trying to convey the
idea that the intervals must be the same between the two time series.

Phillip

**Comment by tritemio** [comment]
Ok, now I understand your point. What about this?

*The classical text-book linear cross-correlation between two signals defined at uniformly-spaced intervals (both signals having the same interval size)*.

**Comment by Phillip-M-Feldman** [comment]
That's perfect.  (Except, "textbook" should be written without a hyphen).
thanks!

**Comment by tritemio** [comment]
Thanks @Phillip-M-Feldman, I committed the fix.
